version: "3.8"

services:

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/postgres_init.sql:/docker-entrypoint-initdb.d/create_tables.sql # see: https://github.com/docker-library/docs/tree/master/postgres#initialization-scripts

  log:
    container_name: logger
    image: prjdevacr.azurecr.io/prj/blockchain-logging-api:707d5a7
    env_file:
      - docker.logger.env
    ports:
      - '4004:4004'

volumes:
  redis:
    driver: local
  pgdata:
    driver: local
